### PR TITLE
#10 Base node server setup

### PR DESCRIPTION
**Pull request by colevoss**

### CODE REVIEW

**Comment by blainekasten** [comment]
I'm about to put up a branch that incorporates adding a css file. Can mine go in first and you add support for the generated css file?

**Comment by colevoss** [comment]
@blainekasten yeah. go for it

**Comment by blainekasten** [comment]
This lgtm

**Review by blainekasten — APPROVED** [review]

**Comment by TheLarkInn** [comment]
Oh shite, is this for SSR? Or just for serving html? There are some larger Archt. changes I'll have to make for SSR with webpack and routing and lazy loading. Would you mind waiting to merge this until I land mine, and we can discuss how we want to go with the page in that regard.

**Pull request closed without merging**
